### PR TITLE
Potential fix for adapter restart loop

### PR DESCRIPTION
**Pull request by tomatenforever**
Within the raised and catched exception the data object is set to null without returning false. However in a later code segment, properties within the data object are read causing an exception that makes the adapter stop. In case the issue persists I see a restart loop for my adapter instance.

### CODE REVIEW

**Comment by tomatenforever** [comment]
@mcm1957 I have mistakenly changed the file `io-package.json` inside this PR, which does not make sense for your repo. I changed the file in order to test the adapter in my local iobroker instance to verify whether the restart loop is gone.

**Comment by mcm1957** [comment]
OK, but if you fix is working create a new PR with the code change.

**Comment by tomatenforever** [comment]
No worries, will do

**Comment by mcm1957** [comment]
THANS for your support

**Comment by tomatenforever** [comment]
@mcm1957 See my changes within [this PR](https://github.com/iobroker-community-adapters/ioBroker.unifi-protect/pull/274)

**Pull request closed without merging**
